Repository dsccommunity/WebAdministrationDsc, pull requests merged in 2018-06, with the labels that each got.

#357 Added custom field logging support to xiisLogging (Fixes #267)
  .gitignore
  DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
  DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.schema.mof
  README.md
  Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1
  Tests/Integration/MSFT_XIISLogging.config.ps1
  Tests/Unit/MSFT_xIISLogging.Tests.ps1
Labels: waiting for code fix

#359 BREAKING CHANGE: Update xIisFeatureDelegation to manage all sections
  DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
  DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.schema.mof
  Examples/Sample_xIisFeatureDelegation_AllowSome.ps1
  Examples/Sample_xIisFeatureDelegation_IisConfigurationPathFormat.ps1
  Examples/Sample_xIisFeatureDelegation_IisModulePathFormat.ps1
  README.md
  Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
  Tests/Integration/MSFT_xIISFeatureDelegation.config.ps1
  Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1
Labels: breaking change, waiting for author response

#362 Update change log in README.md
  README.md
Labels: needs review

#367 Rename customfield class to remove conflict (Fixes #364)
  DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
  DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.schema.mof
  README.md
  Tests/Integration/MSFT_XIISLogging.config.ps1
  Tests/Unit/MSFT_xIISLogging.Tests.ps1
Labels: needs review

#370 Activate the GitHub App Stale on the GitHub repository
  .github/stale.yml
Labels: needs review

#330 Added new xWebConfigProperty & xWebConfigPropertyCollection resources
  DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
  DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.schema.mof
  DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.psm1
  DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.schema.mof
  Examples/Sample_xWebConfigPropertyCollection_Add.ps1
  Examples/Sample_xWebConfigPropertyCollection_Remove.ps1
  Examples/Sample_xWebConfigProperty_Add.ps1
  Examples/Sample_xWebConfigProperty_Remove.ps1
  README.md
  Tests/Integration/MSFT_xWebConfigProperty.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebConfigProperty.config.ps1
  Tests/Integration/MSFT_xWebConfigPropertyCollection.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebConfigPropertyCollection.config.ps1
  Tests/Unit/MSFT_xWebConfigProperty.tests.ps1
  Tests/Unit/MSFT_xWebConfigPropertyCollection.tests.ps1
Labels: needs review

#373 cast $cimLogCustomFields as array fixes #372
  DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
  README.md
Labels: waiting for code fix

#376 Add Integer value support to xWebConfigProperty (fixes #374)
  DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
  Tests/Integration/MSFT_xWebConfigProperty.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebConfigProperty.config.ps1
  Tests/Unit/MSFT_xWebConfigProperty.tests.ps1
Labels: ready for merge
