Repository dsccommunity/WebAdministrationDsc, pull requests merged in 2018-07, with the labels that each got.

#360 xWebAdministration: Add new resource WebApplicationHandler
  DSCResources/Helper.psm1
  DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.psm1
  DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.schema.mof
  DSCResources/MSFT_WebApplicationHandler/en-us/MSFT_WebApplicationHandler.strings.psd1
  Examples/Sample_WebApplicationHandler.ps1
  README.md
  Tests/Integration/MSFT_WebApplicationHandler.Config.ps1
  Tests/Integration/MSFT_WebApplicationHandler.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1
  Tests/Unit/Helper.Tests.ps1
  Tests/Unit/MSFT_WebApplicationHandler.tests.ps1
  Tests/Unit/MSFT_xWebApplication.Tests.ps1
Labels: waiting for code fix

#378 Remove duplicate entries from change log in README.md
  README.md
Labels: needs review

#383 Add Integer property support to xWebConfigPropertyCollection
  DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
  DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.psm1
  Tests/Integration/MSFT_xWebConfigPropertyCollection.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebConfigPropertyCollection.config.ps1
  Tests/Unit/MSFT_xWebConfigPropertyCollection.tests.ps1
Labels: waiting for code fix

#387 fix issue #385 (Timing issue in integration tests)
  Tests/Integration/MSFT_xWebConfigProperty.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebConfigPropertyCollection.Integration.Tests.ps1
Labels: ready for merge

#388 xWebAdministration: Minor typo updates
  README.md
  Tests/Unit/Helper.Tests.ps1
Labels: needs review
