Repository dsccommunity/WebAdministrationDsc, pull requests merged in 2019-10, with the labels that each got.

#500 xWebAdministration: New folder structure for examples
  CHANGELOG.md
  Examples/Resources/WebApplicationHandler/Sample_WebApplicationHandler.ps1
  Examples/Resources/xIisFeatureDelegation/Sample_xIisFeatureDelegation_IisConfigurationPathFormat.ps1
  Examples/Resources/xIisFeatureDelegation/Sample_xIisFeatureDelegation_IisModulePathFormat.ps1
  Examples/Resources/xIisHandler/Sample_xIisHandler_Remove32Bit.ps1
  Examples/Resources/xIisLogging/Sample_xIisLogging_Rollover.ps1
  Examples/Resources/xIisLogging/Sample_xIisLogging_Truncate.ps1
  Examples/Resources/xIisMimeTypeMapping/Sample_xIisMimeTypeMapping_RemoveVideo.ps1
  Examples/Resources/xIisServerDefaults/Sample_xIisServerDefaults.ps1
  Examples/Resources/xSSLSettings/Sample_xSSLSettings_RequireCert.ps1
  Examples/Resources/xWebAppPool/Sample_xWebAppPool.ps1
  Examples/Resources/xWebAppPoolDefaults/Sample_xWebAppPoolDefaults.ps1
  Examples/Resources/xWebApplication/Sample_xWebApplication.ps1
  Examples/Resources/xWebApplication/Sample_xWebApplication_NewWebApplication.ps1
  Examples/Resources/xWebConfigKeyValue/Sample_xWebConfigKeyValue_AddAppSetting.ps1
  Examples/Resources/xWebConfigKeyValue/Sample_xWebConfigKeyValue_RemoveAppSetting.ps1
  Examples/Resources/xWebConfigProperty/Sample_xWebConfigProperty_Add.ps1
  Examples/Resources/xWebConfigProperty/Sample_xWebConfigProperty_Remove.ps1
  Examples/Resources/xWebConfigPropertyCollection/Sample_xWebConfigPropertyCollection_Add.ps1
  Examples/Resources/xWebConfigPropertyCollection/Sample_xWebConfigPropertyCollection_Remove.ps1
  Examples/Resources/xWebSite/Sample_xWebsite_NewWebsite.ps1
  Examples/Resources/xWebSite/Sample_xWebsite_NewWebsiteFromConfigurationData.ps1
  Examples/Resources/xWebSite/Sample_xWebsite_RemoveDefault.ps1
  Examples/Resources/xWebSite/Sample_xWebsite_WithSSLFlags.ps1
  Examples/Resources/xWebSiteDefaults/Sample_xWebSiteDefaults.ps1
  Examples/Resources/xWebVirtualDirectory/Sample_xWebVirtualDirectory_NewVirtualDirectory.ps1
Labels: ready for merge

#501 xWebAdministration: Remove examples README.md
  CHANGELOG.md
  Examples/README.md
Labels: ready for merge

#496 Remove example 'Creating the default website using configuration data' from README.md
  CHANGELOG.md
  README.md
Labels: ready for merge

#506 xIisHandler: Added/updated property descriptions (schema.mof/README.md)
  CHANGELOG.md
  DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.schema.mof
  README.md
Labels: needs review

#508 Update CHANGELOG.md after recent merge
  CHANGELOG.md
Labels: ready for merge

#499 Moved example Sample_xWebsite_StopDefault out from README.md
  CHANGELOG.md
  Examples/Resources/xWebSite/Sample_xWebsite_StopDefault.ps1
  README.md
Labels: needs review

#504 xSslSettings: Updated xSslSettings casing across project
  CHANGELOG.md
  DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.schema.mof
  Examples/Resources/xSSLSettings/Sample_xSSLSettings_RequireCert.ps1
  README.md
  Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1
  Tests/Integration/MSFT_xSSLSettings.config.ps1
  Tests/Unit/MSFT_xSSLSettings.Tests.ps1
Labels: needs review

#505 xWebConfigKeyValue: Updated schema.mof to include description for Ensure
  CHANGELOG.md
  DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.schema.mof
Labels: ready for merge

#507 xWebSite: Updated schema.mof/readme descriptions
  CHANGELOG.md
  DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
  README.md
Labels: ready for merge

#522 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: invalid, ready for merge

#502 xWebAdministration: Alphabetized the resources in README.md
  CHANGELOG.md
  README.md
Labels: ready for merge

#503 xWebAdministration: Adding resource ToC to README.md
  CHANGELOG.md
  README.md
Labels: ready for merge

#519 xWebAppPoolDefaults: Move localization strings to strings.psd1 file
  CHANGELOG.md
  DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
  DSCResources/MSFT_xWebAppPoolDefaults/en-US/MSFT_xWebAppPoolDefaults.strings.psd1
Labels: ready for merge

#510 xIisLogging: Moving strings to localization file
  CHANGELOG.md
  DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
  DSCResources/MSFT_xIisLogging/en-US/MSFT_xIisLogging.strings.psd1
Labels: ready for merge

#511 xIisHandler: Moving strings to localization file
  CHANGELOG.md
  DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
  DSCResources/MSFT_xIIsHandler/en-US/MSFT_xIIsHandler.strings.psd1
Labels: ready for merge

#512 xWebVirtualDirectory: Moving strings to localization file
  CHANGELOG.md
  DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1
  DSCResources/MSFT_xWebVirtualDirectory/en-US/MSFT_xWebVirtualDirectory.strings.psd1
Labels: ready for merge

#513 xIisMimeTypeMapping: Moving strings to localization file
  CHANGELOG.md
  DSCResources/MSFT_xIisMimeTypeMapping/MSFT_xIisMimeTypeMapping.psm1
  DSCResources/MSFT_xIisMimeTypeMapping/en-US/MSFT_xIisMimeTypeMapping.strings.psd1
Labels: ready for merge

#523 xWebAdministration: Optimized exporting in the module manifest for best performance
  CHANGELOG.md
  xWebAdministration.psd1
Labels: needs review

#521 xIisModule: Move localization strings to strings.psd1
  CHANGELOG.md
  DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
  DSCResources/MSFT_xIisModule/en-US/MSFT_xIisModule.strings.psd1
Labels: waiting for code fix

#520 xWebApplication: Move localization strings to strings.psd1 file #468
  CHANGELOG.md
  DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
  DSCResources/MSFT_xWebApplication/en-US/MSFT_xWebApplication.strings.psd1
Labels: ready for merge

#517 xWebConfigProperty: Move localization strings to strings.psd1 file
  CHANGELOG.md
  DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
  DSCResources/MSFT_xWebConfigProperty/en-US/MSFT_xWebConfigProperty.strings.psd1
Labels: ready for merge

#525 BREAKING CHANGE: xWebAppPoolDefaults: Align to best practices for single instance resource
  CHANGELOG.md
  DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
  DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.schema.mof
  Examples/Resources/xIisServerDefaults/Sample_xIisServerDefaults.ps1
  Examples/Resources/xWebAppPoolDefaults/Sample_xWebAppPoolDefaults.ps1
  README.md
  Tests/Integration/MSFT_xWebAppPoolDefaults.config.ps1
  Tests/Unit/MSFT_xWebAppPoolDefaults.Tests.ps1
Labels: breaking change

#515 xWebSiteDefaults: Move localization strings to strings.psd1
  CHANGELOG.md
  DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
  DSCResources/MSFT_xWebSiteDefaults/en-US/MSFT_xWebSiteDefaults.strings.psd1
Labels: ready for merge

#516 xWebConfigPropertyCollection: Move localization strings to strings.psd1
  CHANGELOG.md
  DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.psm1
  DSCResources/MSFT_xWebConfigPropertyCollection/en-US/MSFT_xWebConfigPropertyCollection.strings.psd1
Labels: ready for merge

#518 xWebConfigKeyValue: Move localization strings to strings.psd1 file
  CHANGELOG.md
  DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1
  DSCResources/MSFT_xWebConfigKeyValue/en-US/MSFT_xWebConfigKeyValue.strings.psd1
Labels: ready for merge

#527 BREAKING CHANGE: xWebSiteDefaults: Align to best practices
  CHANGELOG.md
  DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
  DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.schema.mof
  Examples/Resources/xIisServerDefaults/Sample_xIisServerDefaults.ps1
  Examples/Resources/xWebSiteDefaults/Sample_xWebSiteDefaults.ps1
  README.md
  Tests/Integration/MSFT_xWebAppPoolDefaults.config.ps1
  Tests/Integration/MSFT_xWebsiteDefaults.config.ps1
Labels: breaking change, ready for merge

#528 xWebApplication: Update descriptions in class xWebApplicationAuthenticationInformation
  CHANGELOG.md
  DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.schema.mof
Labels: ready for merge

#526 xWebAdministration: Move example to separate file
  CHANGELOG.md
  Examples/Resources/Sample_EndToEndxWebAdministration.ps1
  README.md
Labels: waiting for code fix

#530 xWebAdministration: Style guide update for hashtables
  CHANGELOG.md
  DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
  DSCResources/MSFT_xIisMimeTypeMapping/MSFT_xIisMimeTypeMapping.psm1
  DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
  DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
  DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
  DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.psm1
  DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
  xWebAdministration.psd1
Labels: ready for merge

#531 xIisFeatureDelegation: xSslSettings: Moved localization strings
  CHANGELOG.md
  DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
  DSCResources/MSFT_xIisFeatureDelegation/en-US/MSFT_xIisFeatureDelegation.strings.psd1
  DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.psm1
  DSCResources/MSFT_xSSLSettings/en-US/MSFT_xSslSettings.strings.psd1
Labels: needs review

#532 xWebAppPool: Moved MSFT_xWebAppPool localization strings
  CHANGELOG.md
  DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
  DSCResources/MSFT_xWebAppPool/en-US/MSFT_xWebAppPool.strings.psd1
Labels: ready for merge

#537 xSslSettings: Resolve Casing in Name
  CHANGELOG.md
  DSCResources/MSFT_xSslSettings/MSFT_xSslSettings.psm1
  DSCResources/MSFT_xSslSettings/MSFT_xSslSettings.schema.mof
  DSCResources/MSFT_xSslSettings/en-US/MSFT_xSslSettings.strings.psd1
  Examples/Resources/xSslSettings/Sample_xSslSettings_RequireCert.ps1
  README.md
  Tests/Integration/MSFT_xSslSettings.Integration.Tests.ps1
  Tests/Integration/MSFT_xSslSettings.config.ps1
  Tests/Integration/MSFT_xSslSettings.config.psd1
  Tests/Unit/MSFT_xSslSettings.Tests.ps1
Labels: needs review

#538 xWebSite: Resolve Resource Name Case
  CHANGELOG.md
  DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1
  DSCResources/MSFT_xWebSite/MSFT_xWebSite.schema.mof
  DSCResources/MSFT_xWebSite/en-US/MSFT_xWebSite.strings.psd1
  Examples/Resources/xWebApplication/Sample_xWebApplication_NewWebApplication.ps1
  Examples/Resources/xWebSite/Sample_xWebSite_NewWebsite.ps1
  Examples/Resources/xWebSite/Sample_xWebSite_NewWebsiteFromConfigurationData.ps1
  Examples/Resources/xWebSite/Sample_xWebSite_NewWebsite_UsingCertificateSubject.ps1
  Examples/Resources/xWebSite/Sample_xWebSite_NewWebsite_UsingCertificateThumbprint.ps1
  Examples/Resources/xWebSite/Sample_xWebSite_RemoveDefault.ps1
  Examples/Resources/xWebSite/Sample_xWebSite_StopDefault.ps1
  Examples/Resources/xWebSite/Sample_xWebSite_WithSSLFlags.ps1
  Examples/Resources/xWebVirtualDirectory/Sample_xWebVirtualDirectory_NewVirtualDirectory.ps1
  README.md
  Tests/Integration/MSFT_xWebSite.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebSite.config.ps1
  Tests/Integration/MSFT_xWebSite.config.psd1
  Tests/Integration/MSFT_xWebSiteDefaults.Integration.Tests.ps1
  Tests/Integration/MSFT_xWebSiteDefaults.config.ps1
  Tests/Unit/MSFT_xWebsite.Tests.ps1
  xWebAdministration.psd1
Labels: ready for merge

#540 xWebAdministration: Updating change log prior to release
  CHANGELOG.md
Labels: ready for merge
